#!/usr/bin/perl

use strict;

use URI::Escape;

my $agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_8) AppleWebKit/535.2 (KHTML, like Gecko) Chrome/15.0.874.121 Safari/535.2';

my @multiverseids = (174808, 174922);

foreach my $id (@multiverseids) {
	my $url = 'http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=' . $id;
	my $cmd = 'curl -s -L -A ' . "'" . 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_8) AppleWebKit/535.2 (KHTML, like Gecko) Chrome/15.0.874.121 Safari/535.2' . "' " . $url . ' > card_html/' . $id . '.html';
	#print "$id";
	#`$cmd`;
	#`sleep 3`;
}

my @names = ("Animar, Soul of Elements",
"Forest",
"Island",
"Mountain",
"Novijen, Heart of Progress",
"Simic Growth Chamber",
"Valakut, the Molten Pinnacle",
"Rupture Spire",
"Kazandu Refuge",
"Izzet Boilerworks",
"Homeward Path",
"Gruul Turf",
"Evolving Wilds",
"Command Tower",
"Vivid Grove",
"Vivid Creek",
"Vivid Crag",
"Temple of the False God",
"Fungal Reaches",
"Garruk Wildspeaker",
"Hull Breach",
"Hunting Pack",
"Soul's Might",
"Colossal Might",
"Electropotence",
"Lead the Stampede",
"Strength of the Tajuru",
"Fastbond",
"Pemmin's Aura",
"Soul's Fire",
"Ruination",
"Ray of Command",
"Invert the Skies",
"Exclude",
"Essence Scatter",
"Dissipate",
"Fuel for the Cause",
"Negate",
"Cancel",
"Spellbook",
"Eldrazi Monument",
"Lightning Greaves",
"Intet, the Dreamer",
"Deadly Recluse",
"Inkwell Leviathan",
"Grozoth",
"Verdant Force",
"Borborygmos",
"Bringer of the Red Dawn",
"Liege of the Tangle",
"Fierce Empath",
"Artisan of Kozilek",
"Ulamog, the Infinite Gyre",
"Primordial Sage",
"Drumhunter",
"Lumberknot",
"Falkenrath Marauders",
"Scourge of Geier Reach",
"Murder of Crows",
"Bellowing Tanglewurm",
"Garruk's Packleader",
"Riku of Two Reflections",
"Rapacious One",
"Hydra Omnivore",
"Magmatic Force",
"Simic Sky Swallower",
"Carnage Wurm",
"Primordial Hydra",
"Palinchron",
"Jin-Gitaxias, Core Augur",
"Symbiotic Wurm",
"Stingerfling Spider",
"Grazing Gladehart",
"Ulamog's Crusher",
"Wall of Frost",
"Phyrexian Metamorph",
"Bringer of the Green Dawn",
"Experiment Kraj",
"Grim Lavamancer",
"Hellspark Elemental",
"Jackal Pup",
"Jaya Ballard, Task Mage",
"Keldon Champion",
"Keldon Marauders",
"Mogg Fanatic",
"Mogg Flunkies",
"Spark Elemental",
"Vulshok Sorcerer",
"Browbeat",
"Chain Lightning",
"Fireball",
"Fireblast",
"Flames of the Blood Hand",
"Hammer of Bogardan",
"Lightning Bolt",
"Pillage",
"Price of Progress",
"Reverberate",
"Sudden Impact",
"Thunderbolt",
"Inkmoth Nexus",
"Misty Rainforest",
"Blighted Agent",
"Glistener Elf",
"Ichorclaw Myr",
"Apostle's Blessing",
"Distortion Strike",
"Gitaxian Probe",
"Groundswell",
"Livewire Lash",
"Mutagenic Growth",
"Vines of Vastwood",
"Nature's Claim",
"Spell Pierce",
"Spellskite",
"Viridian Corrupter",
"Swamp",
"Ghost Quarter",
"Liliana of the Veil",
"Bloodline Keeper",
"Victim of Night",
"Moan of the Unhallowed",
"Vampiric Fury",
"Galvanic Juggernaut",
"Furor of the Bitten",
"Ghoulraiser",
"Infernal Plunge",
"Feral Ridgewolf",
"Manor Skeleton",
"Walking Corpse",
"Night Revelers",
"Scourge of Geier Reach",
"Stromkirk Patrol",
"Geistflame",
"Into the Maw of Hell",
"Dead Weight",
"Tribute to Hunger",
"Manor Skeleton",
"Spectral Flight",
"Wooden Stake",
"Corpse Lunge",
"Forbidden Alchemy",
"Tormented Pariah",
"Night Terrors",
"Curse of Oblivion",
"Gruesome Deformity",
"Moonmist",
"Cobbled Wings",
"Kindercatch",
"Past in Flames",
"Rooftop Storm",
"Heretic's Punishment",
"Unburial Rites",
"Frightful Delusion",
"Memory's Journey",
"Claustrophobia",
"Burning Vengeance",
"Plains",
"Gavony Township",
"Avacyn's Pilgrim",
"Elite Inquisitor",
"Gideon's Lawkeeper",
"Serra Angel",
"Suture Priest",
"Hero of Bladehold",
"Tree of Redemption",
"Mirran Crusader",
"Caravan Vigil",
"Guardians' Pledge",
"Sickleslicer",
"Honor of the Pure",
"Shrine of Loyal Legions",
"Travel Preparations",
"Bonds of Faith",
"Mask of Avacyn",
"Timely Reinforcements",
"Plains",
"Swamp",
"Bloodline Keeper",
"Cloistered Youth",
"Diregraf Ghoul",
"Doomed Traveler",
"Markov Patrician",
"Screeching Bat",
"Skirsdag High Priest",
"Stromkirk Patrol",
"Thraben Purebloods",
"Thraben Sentry",
"Unruly Mob",
"Walking Corpse",
"Altar's Reap",
"Curse of Death's Hold",
"Ghoulcaller's Chant",
"Midnight Haunting",
"Moment of Heroism",
"Smite the Monstrous",
"Unburial Rites",
"Civilized Scholar",
"Creeping Renaissance",
"Curse of the Bloody Tome",
"Dream Twist",
"Frightful Delusion",
"Ghostly Possession",
"Hysterical Blindness",
"Infernal Plunge",
"Intangible Virtue",
"Invisible Stalker",
"Memory's Journey",
"Moonmist",
"Nightbird's Clutches",
"Paraselene",
"Runic Repetition",
"Spare from Evil",
"Woodland Sleuth",
"Bloodgift Demon",
"Bloodline Keeper",
"Cloistered Youth",
"Diregraf Ghoul",
"Doomed Traveler",
"Markov Patrician",
"Screeching Bat",
"Skirsdag High Priest",
"Stromkirk Patrol",
"Thraben Purebloods",
"Thraben Sentry",
"Unruly Mob",
"Walking Corpse",
"Altar's Reap",
"Curse of Death's Hold",
"Ghoulcaller's Chant",
"Midnight Haunting",
"Moment of Heroism",
"Smite the Monstrous",
"Unburial Rites",
"Civilized Scholar",
"Creeping Renaissance",
"Curse of the Bloody Tome",
"Dream Twist",
"Frightful Delusion",
"Ghostly Possession",
"Hysterical Blindness",
"Infernal Plunge",
"Intangible Virtue",
"Invisible Stalker",
"Memory's Journey",
"Moonmist",
"Nightbird's Clutches",
"Paraselene",
"Runic Repetition",
"Spare from Evil",
"Ashmouth Hound",
"Bloodcrazed Neonate",
"Delver of Secrets",
"Feral Ridgewolf",
"Kessig Wolf",
"Lantern Spirit",
"Rage Thrower",
"Rakish Heir",
"Skirsdag Cultist",
"Village Ironsmith",
"Brimstone Volley",
"Butcher's Cleaver",
"Feeling of Dread",
"Forbidden Alchemy",
"Geistflame",
"Into the Maw of Hell",
"Silent Departure",
"Think Twice",
"Traitorous Blood",
"Traveler's Amulet",
"Altar's Reap",
"Frightful Delusion",
"Furor of the Bitten",
"Ghost Quarter",
"Gnaw to the Bone",
"Kessig Wolf",
"Maw of the Mire",
"Mulch",
"Orchard Spirit",
"Purify the Grave",
"Skeletal Grimace",
"Spare from Evil",
"Spider Spawning",
"Spidery Grasp",
"Vampire Interloper",
"Vampiric Fury",
"Wreath of Geists",
"Ambush Viper",
"Avacynian Priest",
"Darkthicket Wolf",
"Festerhide Boar",
"Fiend Hunter",
"Galvanic Juggernaut",
"Hamlet Captain",
"Lumberknot",
"Selfless Cathar",
"Village Bell-Ringer",
"Villagers of Estwald",
"Voiceless Spirit",
"Woodland Sleuth",
"Blazing Torch",
"Bonds of Faith",
"Prey Upon",
"Ranger's Guile",
"Rebuke",
"Sharpened Pitchfork",
"Smite the Monstrous",
"Spidery Grasp",
"Ancient Grudge",
"Doomed Traveler",
"Gnaw to the Bone",
"Grizzled Outcasts",
"Inquisitor's Flail",
"Kindercatch",
"Make a Wish",
"Manor Skeleton",
"Maw of the Mire",
"Moonmist",
"Paraselene",
"Rooftop Storm",
"Thraben Purebloods",
"Urgent Exorcism",
"Woodland Sleuth",
"Ashmouth Hound",
"Bloodcrazed Neonate",
"Geistcatcher's Rig",
"Kruin Outlaw",
"Markov Patrician",
"Pitchburn Devils",
"Rage Thrower",
"Riot Devils",
"Scourge of Geier Reach",
"Skirsdag Cultist",
"Stromkirk Noble",
"Village Cannibals",
"Village Ironsmith",
"Army of the Damned",
"Blazing Torch",
"Bump in the Night",
"Butcher's Cleaver",
"Corpse Lunge",
"Dead Weight",
"Harvest Pyre",
"Heretic's Punishment",
"Moan of the Unhallowed",
"Tribute to Hunger",
"Victim of Night",
"Ambush Viper",
"Ancient Grudge",
"Boneyard Wurm",
"Ghoulraiser",
"Graveyard Shovel",
"Moldgraf Monstrosity",
"Night Terrors",
"Rally the Peasants",
"Ranger's Guile",
"Selfless Cathar",
"Shimmering Grotto",
"Spider Spawning",
"Stromkirk Patrol",
"Tree of Redemption",
"Ulvenwald Mystics",
"Vampiric Fury",
"Armored Skaab",
"Avacyn's Pilgrim",
"Darkthicket Wolf",
"Gatstaf Shepherd",
"Hollowhenge Scavenger",
"Ludevic's Test Subject",
"Makeshift Mauler",
"Mayor of Avabruck",
"Moon Heron",
"Murder of Crows",
"One-Eyed Scarecrow",
"Orchard Spirit",
"Pitchburn Devils",
"Selhoff Occultist",
"Brimstone Volley",
"Caravan Vigil",
"Harvest Pyre",
"Prey Upon",
"Ranger's Guile",
"Spectral Flight",
"Spidery Grasp",
"Travel Preparations",
"Altar's Reap",
"Brain Weevil",
"Cobbled Wings",
"Curse of Oblivion",
"Curse of the Nightly Hunt",
"Feral Ridgewolf",
"Grave Bramble",
"Grizzled Outcasts",
"Mask of Avacyn",
"Naturalize",
"Sharpened Pitchfork",
"Thraben Sentry",
"Traitorous Blood",
"Wooden Stake",
"Ashmouth Hound",
"Battleground Geist",
"Fortress Crab",
"One-Eyed Scarecrow",
"Selhoff Occultist",
"Sturmgeist",
"Tormented Pariah",
"Burning Vengeance",
"Claustrophobia",
"Curse of the Bloody Tome",
"Desperate Ravings",
"Dissipate",
"Dream Twist",
"Forbidden Alchemy",
"Ghoulcaller's Bell",
"Into the Maw of Hell",
"Sensory Deprivation",
"Think Twice",
"Avacynian Priest",
"Back from the Brink",
"Bramblecrush",
"Curse of the Pierced Heart",
"Ghoulcaller's Chant",
"Hollowhenge Scavenger",
"Intangible Virtue",
"Laboratory Maniac",
"Lumberknot",
"Memory's Journey",
"Night Revelers",
"Past in Flames",
"Reckless Waif",
"Scourge of Geier Reach",
"Tormented Pariah",
"Typhoid Rats",
"Vampiric Fury",
"Witchbane Orb",
"Plains",
"Abbey Griffin",
"Champion of the Parish",
"Chapel Geist",
"Delver of Secrets",
"Doomed Traveler",
"Elder Cathar",
"Geist-Honored Monk",
"Invisible Stalker",
"Selfless Cathar",
"Spectral Rider",
"Stitcher's Apprentice",
"Unruly Mob",
"Voiceless Spirit",
"Dissipate",
"Feeling of Dread",
"Grasp of Phantoms",
"Lost in the Mist",
"Silver-Inlaid Dagger",
"Smite the Monstrous",
"Abbey Griffin",
"Cobbled Wings",
"Furor of the Bitten",
"Ghostly Possession",
"Gruesome Deformity",
"Heartless Summoning",
"Hysterical Blindness",
"Infernal Plunge",
"Nevermore",
"Night Terrors",
"Nightbird's Clutches",
"Sensory Deprivation",
"Somberwald Spider",
"Spare from Evil",
"Thraben Purebloods",
"Urgent Exorcism",
"Wooden Stake",
"Island",
"Swamp",
"Abattoir Ghoul",
"Armored Skaab",
"Battleground Geist",
"Deranged Assistant",
"Fortress Crab",
"Makeshift Mauler",
"Skaab Goliath",
"Snapcaster Mage",
"Stitched Drake",
"Stromkirk Patrol",
"Typhoid Rats",
"Vampire Interloper",
"Walking Corpse",
"Cackling Counterpart",
"Corpse Lunge",
"Curiosity",
"Dead Weight",
"Ghoulcaller's Chant",
"Grasp of Phantoms",
"Victim of Night",
"Bitterheart Witch",
"Brain Weevil",
"Creepy Doll",
"Fortress Crab",
"Ghoulcaller's Bell",
"Graveyard Shovel",
"Inquisitor's Flail",
"Intangible Virtue",
"Manor Skeleton",
"Moment of Heroism",
"Night Revelers",
"Nightbird's Clutches",
"Rebuke",
"Silverchase Fox",
"Typhoid Rats",
"Voiceless Spirit",
"Woodland Cemetery",
);

my $search_url_base = 'http://gatherer.wizards.com/Pages/Search/Default.aspx?name=';

foreach my $name (@names) {
	my $fn = $name;
	$fn =~ s/(\W)/_/gi;
	if (! -e "card_html/$fn.html") {
		my $url = $search_url_base . &mkQuery($name);
		my $cmd = 'curl -g -s -L -A \'' . $agent . '\' ' . $url . " > card_html/$fn.html";
		print "$name - downloading...\n";
		`$cmd`;
		`sleep 2`;
	} else {
		print "$name - skipping...\n";
	}
}

sub mkQuery {
	my $term = shift;
	my @ts = split(/\s+/, $term);
	my $result = '';
	foreach my $t (@ts) {
		$result = $result . '+[' . uri_escape($t) . ']';
	}
	$result =~ s/'/\\'/gi;
	return $result;
}
